unique_ids:
  assets:
    standard-page.html: 7LJEAMS2NZ5AN2NK6YTHPI6NXM57SXZZ
    theme.css: KUVB5OJQVMMZR6I7XQTQAJ44ABVHFTC6
  forms:
    AboutUs: '1706487085090307943951287.49384'
    ContactUs: '1706488321970715680747019.729'
    Homepage: BMLJKVRHBO6QVXQVTAMMKFH5KAEMQWA3
  modules: {}
  scripts: {}
  server_modules: {}
